### PR TITLE
Add note about services vs. workloads

### PR DESCRIPTION
**Pull request by aquarhead**

### CODE REVIEW

**Comment by aphyr** [comment]
Ah--this isn't actually something the kv workload will actually generate, which is why it isn't a part of the spec. If you're thinking about the lin-kv service, it might be good to add a separate set of RPC calls for that.

**Comment by aquarhead** [comment]
Ah I see, so the `workloads.md` only meant to describe messages from maelstrom to my implementation code? (just confirming I'm understanding it correctly).

I was indeed referencing `workloads.md` for all my message structures, so got confused when doing [this](https://github.com/jepsen-io/maelstrom/blob/50608759036ebd5da6b3d113a8df93734763f6a2/doc/05-datomic/02-shared-state.md#keys-in-lin-kv) and can't find `create_if_not_exists` in workloads.

Maybe we can simply mention it in the tutorials?

**Comment by aphyr** [comment]
Yeah, feel free to mention it there. It's also documented in the https://github.com/jepsen-io/maelstrom/blob/main/doc/services.md#lin-kv lin-kv docs.

**Comment by aquarhead** [comment]
My bad, didn't notice that page (`services.md`) 😂

**Comment by aphyr** [comment]
Thanks!

**Pull request merged**
